# Task 4


### 1.What does the size attribute in numpy use to find?

> - A) number of items
> - B) shape
> - C) date & time
> - D) unique items

In [2]:
## answer is : A) number of items
#EX:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a.size)


4


### 2.What method is used for changing the shape of numpy arrays?

> - A) shape()
> - B) change_shape()
> - C) update_shape()
> - D) reshape()

In [1]:
## answer is : D) reshape()
# EX:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)

[[1 2 3]
 [4 5 6]]


### 3.What is the purpose of zero() function?

> - A) To create a matrix with the first row and first column as 0
> - B) To create a matrix with diagonal elements as 0
> - C) To create a matrix with all elements as 0
> - D) To return an integer number 0

In [4]:
## answer is :  C) To create a matrix with all elements as 0
# EX:
import numpy as np

zero_matrix = np.zeros((2, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


### 4.Why do we use ndim?

> - A) To find the size of an array
> - B) To find the dimension of an array
> - C) To find the number of elements in an array
> - D) There is no such thing as ndim

In [7]:
## answer is : B) To find the dimension of an array
# EX:

import numpy as np

arr_1D = np.array([1,2,3])
arr_2D = np.array([[1,2,3],[4,5,6]])
arr_3D = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])

print(np.ndim(arr_1D))
print(np.ndim(arr_2D))
print(np.ndim(arr_3D))


1
2
3


<h1><font color='brown'> Answer these question

## 1- create 1D, 2D and 3D arrays in NumPy? then returns the type of the elements stored in the NumPy array.

In [8]:
# One-Dimensional array
arr_1D = np.array([1,2,3])
print(arr_1D.dtype)


int64


In [10]:
# Two-Dimensional array
arr_2D = np.array([[1,2,3],[4,5,6]])
print(arr_2D.dtype)


int64


In [9]:
# Three-Dimensional array
arr_3D = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(arr_3D.dtype)

int64


## 2-Reverse this array [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]] in two ways......

In [18]:
# Method one
arr = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
print(arr[...,::-1])

[[[ 4  3  2  1]
  [ 7  6  5  4]
  [10  9  8  7]]]


In [23]:
# Method two
#>**hint**: use flipud function
arr2 = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
print(np.flipud(arr2))

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]


## -Display the size & length of the array

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

#size
print(arr.size)

#len
print(len(arr))

6
2


[link text](https://\)## -Make this array as an array one dimensional

In [28]:
arr_1d = arr.flatten()
print(arr_1d)



[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
# or
print(arr.reshape(-1))

## 3-make an array using random function with size (2,3) & with integer values
>**hint**: use seed function to make numbers not change

In [44]:
np.random.seed(40)
random_array = np.random.randint(0, 10, size=(2, 3))
print(random_array)

[[5 8 9]
 [5 0 0]]


## -Transpose this array

In [49]:
print(np.transpose(random_array))

[[5 5]
 [8 0]
 [9 0]]


## 4-How is np.mean() different from np.average() in NumPy?

In [52]:
# np.average() is use to compute a weighted average:

#mean:
a = np.array([1, 2, 3, 4])
print(np.mean(a))

#average:
weights = np.array([0.1, 0.2, 0.5, 0.2])
print(np.average(a, weights=weights))

2.5
2.8


## 5-Count the frequency of a given positive value appearing in this NumPy array
## [1, 2, 1, 3, 5, 0, 0, 0, 2, 3] ?

In [55]:
arr = np.array([1, 2, 1, 3, 5, 0, 0, 0, 2, 3])

for value in set(arr):
  count = np.count_nonzero(arr == value)
  print(f"Frequency of {value}: {count}")  # Output: 2

Frequency of 0: 3
Frequency of 1: 2
Frequency of 2: 2
Frequency of 3: 2
Frequency of 5: 1


## 6-Show how is arr[:,0] different from arr[:,[0]]\

In [57]:
# 1) arr[:,0]
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[:,0])

# Vector
# select all rows and the 1st column


[1 4 7]


In [59]:
# 1) arr[:,0]
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[:,[0]])

# Matrix
# select all rows and one column from the columns

[[1]
 [4]
 [7]]


## 7-How do you multiply these 2 NumPy array matrices [[15,16,17],[18,19,20],[21,22,23]]  &  [[20,21,22],[23,24,25],[26,27,28]] ?

In [60]:
# 1) element-wise
A = np.array([[15, 16, 17],
              [18, 19, 20],
              [21, 22, 23]])

B = np.array([[20, 21, 22],
              [23, 24, 25],
              [26, 27, 28]])

print(A * B)

[[300 336 374]
 [414 456 500]
 [546 594 644]]


In [61]:
# 2) matrix multiplication

AB = np.dot(A,B)
print(AB)

[[1110 1158 1206]
 [1317 1374 1431]
 [1524 1590 1656]]


## -Combine these 2 NumPy arrays [1,2,3] & [4,5,6] using vstack()     and hstack()

In [67]:
V_stack = np.vstack((A,B))
print(V_stack)

[[15 16 17]
 [18 19 20]
 [21 22 23]
 [20 21 22]
 [23 24 25]
 [26 27 28]]


In [66]:
H_stack = np.hstack((A,B))
print(H_stack)

[[15 16 17 20 21 22]
 [18 19 20 23 24 25]
 [21 22 23 26 27 28]]


<h1><font color='brown'> Solve These Problems

<a href='https://codeforces.com/problemset/problem/339/A'> **problem 1**

In [ ]:
# Problem_1 Link:
arr = input().split('+')
arr = sorted(arr)
print('+'.join(arr))

# Link: https://codeforces.com/contest/339/submission/318383079


<a href='https://codeforces.com/problemset/problem/118/A'> **problem 2**

In [ ]:
# Problem_2 Link:
s = input().strip()
vowels = {'a', 'o', 'y', 'e', 'u', 'i'}
result = []
for char in s:
    lower_char = char.lower()
    if lower_char not in vowels:
        result.append('.')
        result.append(lower_char)
print(''.join(result))

# Link: https://codeforces.com/contest/118/submission/318383399